# Generated by Django 5.2.17 on 2026-08-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='contact_videos/'),
        ),
    ]
