# Generated by Django 5.2.17 on 2026-08-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contactmessage_image_contactmessage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
