# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course_access_approved',
            field=models.BooleanField(default=False),
        ),
    ]
