# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_customuser_course_access_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model(
                "shop", "CustomUser"
            ).objects.filter(phone_number="").update(phone_number=None),
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]