# Generated by Django 5.2.17 on 2026-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
