# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_authsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='access_jti',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
