# Generated by Django 5.2.17 on 2026-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_lesson_thumbnail_url_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
