# Generated by Django 5.2.17 on 2026-08-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_course_video_path_lesson_thumbnail_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail_path',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_path',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_path',
        ),
    ]
