# Generated by Django 5.2.17 on 2026-09-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_lesson_thumbnail_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='detected_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='detected_language_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtitle_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtitle_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=15)),
                ('language_name', models.CharField(max_length=50)),
                ('is_original', models.BooleanField(default=False)),
                ('vtt_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('srt_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('vtt_content', models.TextField(blank=True, default='')),
                ('srt_content', models.TextField(blank=True, default='')),
                ('cues_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='shop.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='shop.lesson')),
            ],
            options={
                'ordering': ['language_name'],
                'unique_together': {('lesson', 'language_code')},
            },
        ),
    ]
