# Generated by Django 5.1.15 on 2026-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_subtitlesetting_lesson_detected_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Optional banner title or alt text', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Banner image file', null=True, upload_to='promotional_banners/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Direct image URL if hosted externally or via CDN')),
                ('link_url', models.URLField(blank=True, default='', help_text='Destination URL when banner is clicked', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
